[package]
name = "naia-hecs-client"
# 0.19 is unpublished for now, due to lack of use of this crate, as well as plans for rapid releases - 2/28/2023
version = "0.19.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
workspace = "../../.."
description = "Library to faciliate naia_client & Hecs interop"
homepage = "https://github.com/naia-lib/naia"
repository = "https://github.com/naia-lib/naia"
keywords = ["wasm", "webrtc", "udp", "networking", "gamedev"]
categories = ["network-programming", "game-development", "wasm", "web-programming"]
license = "MIT OR Apache-2.0"
edition = "2021"

[badges]
maintenance = { status = "actively-developed" }

[features]
wbindgen = [ "naia-client/wbindgen", "naia-hecs-shared/wbindgen" ]
mquad = [ "naia-client/mquad", "naia-hecs-shared/mquad" ]
transport_webrtc = [ "naia-client/transport_webrtc" ]
transport_udp = [ "naia-client/transport_udp" ]

[dependencies]
naia-client = { version = "0.19", path = "../../../client" }
naia-hecs-shared = { version = "0.19", path = "../shared" }
hecs = { version = "0.9" }