[package]
name = "naia-bevy-client"
version = "0.23.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
workspace = "../../.."
description = "Library to faciliate naia_client & Bevy interop"
homepage = "https://github.com/naia-lib/naia"
repository = "https://github.com/naia-lib/naia"
license = "MIT OR Apache-2.0"
edition = "2021"

[badges]
maintenance = { status = "actively-developed" }

[features]
transport_webrtc = [ "naia-client/transport_webrtc" ]
transport_udp = [ "naia-client/transport_udp" ]

[dependencies]
naia-client = { version = "0.23", path = "../../../client", features = ["bevy_support", "wbindgen"] }
naia-bevy-shared = { version = "0.23", path = "../shared" }
bevy_app = { version = "0.14", default-features=false }
bevy_ecs = { version = "0.14", default-features=false }
log = { version = "0.4" }