[package]
name = "naia-bevy-server-demo"
version = "0.1.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
workspace = "../../../"
publish = false
edition = "2018"
license = "MIT OR Apache-2.0"

[features]
use-udp = [ "naia-bevy-server/use-udp" ]
use-webrtc = [ "naia-bevy-server/use-webrtc" ]

[dependencies]
naia-bevy-demo-shared = { path = "../shared" }
naia-bevy-server = { path = "../../../adapters/bevy/server" }
bevy = { version="0.6.0", default-features=false }