[package]
name = "naia-bevy-shared"
version = "0.10.2"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
workspace = "../../.."
description = "Library to faciliate naia & Bevy interop, functionality shared by client & server versions"
homepage = "https://github.com/naia-rs/naia"
repository = "https://github.com/naia-rs/naia"
license = "MIT OR Apache-2.0"
edition = "2021"

[badges]
maintenance = { status = "actively-developed" }

[features]

[dependencies]
naia-shared = { version = "^0.10", path = "../../../shared", features = ["bevy_support", "wbindgen"] }
bevy_ecs = { version = "0.8", default-features=false }
