[package]
name = "naia-server"
version = "0.7.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
description = "A server that uses either UDP or WebRTC communication to send/receive messages to/from connected clients, and syncs registered Entities/Components to clients to whom they are in-scope."
documentation = "https://docs.rs/naia-server"
homepage = "https://github.com/naia-rs/naia"
repository = "https://github.com/naia-rs/naia"
readme = "../README.md"
keywords = ["webrtc", "udp", "server", "networking", "gamedev"]
license = "MIT OR Apache-2.0"
categories = ["network-programming", "game-development", "wasm", "web-programming"]
edition = "2018"

[badges]
maintenance = { status = "actively-developed" }

[package.metadata.docs.rs]
features = [ "use-webrtc" ]

[features]
use-udp = [ "naia-server-socket/use-udp" ]
use-webrtc = [ "naia-server-socket/use-webrtc" ]
bevy-support = ["naia-shared/bevy-support"]

[dependencies]
naia-server-socket = { version = "=0.7.0" }
naia-shared = { path = "../shared", version = "=0.7.0" }
log = "0.4"
slotmap = { version = "0.4" }
byteorder = "1.3"
ring = "0.16.15"
futures-util = { version = "0.3", features = ["sink"] }
async-io = { version = "1.1" }
futures-core = { version = "0.3" }
cfg-if = "0.1.10"
