[package]
name = "naia-basic-client-demo-wb"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
workspace = "../../.."
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[features]

[dependencies]
naia-basic-client-demo-app = { path = "../app", features = [ "wbindgen" ] }
log = "0.4"
cfg-if = "0.1.10"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
simple_logger = { version = "=2.0.0" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-logger = { version = "0.2.0" }
wasm-bindgen = { version = "0.2.45", features = [ "serde-serialize" ] }
web-sys = { version = "0.3.4", features = [ 'Window' ] }