[package]
name = "naia-bevy-demo-shared"
version = "0.1.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
workspace = "../../../"
publish = false
edition = "2018"
license = "MIT OR Apache-2.0"

[features]

[dependencies]
bevy_ecs = { version="=0.6.0", default-features=false}
naia-shared = { path = "../../../shared" }
naia-derive = { path = "../../../derive" }
cfg-if = "0.1.10"
log = "0.4"
nanoserde = "0.1.17"