[package]
name = "naia-macroquad-server-demo"
version = "0.1.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
workspace = "../../.."
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
naia-server = { path = "../../../server" }
naia-server-socket = { path = "../../../socket/server" }
naia-demo-world = { path = "../../demo_utils/demo_world" }
naia-macroquad-demo-shared = { path = "../shared" }
log = { version = "0.4" }
simple_logger = { version = "4.0", default-features = false, features = ["timestamps"] }