[package]
name = "naia-shared"
version = "0.7.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
description = "Common functionality shared between naia-server & naia-client crates"
documentation = "https://docs.rs/naia-shared"
homepage = "https://github.com/naia-rs/naia"
repository = "https://github.com/naia-rs/naia"
readme = "../README.md"
keywords = ["webrtc", "udp", "wasm", "networking", "gamedev"]
license = "MIT OR Apache-2.0"
categories = ["network-programming", "game-development", "wasm", "web-programming"]
edition = "2018"

[badges]
maintenance = { status = "actively-developed" }

[features]
wbindgen = [ "naia-socket-shared/wbindgen" ]
mquad = [ "naia-socket-shared/mquad" ]
bevy-support = [ "bevy" ]

[dependencies]
naia-socket-shared = { version = "=0.7.0" }
byteorder = "1.3"
log = "0.4"
nanoserde = "0.1.29"
bevy = { version = "0.6", default_features = false, optional = true }
