[package]
name = "naia-shared"
version = "0.1.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
edition = "2018"

[dependencies]
naia-socket-shared = { version = "0.1.0" }
byteorder = "1.3"
log = "0.4"
cfg-if = "0.1.10"

[target.'cfg(target_arch = "wasm32")'.dependencies]
# wasm-bindgen = { version = "0.2.45", features = [ ] }
js-sys = "0.3"