[package]
name = "naia-bevy-server"
version = "0.7.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
description = "Library to faciliate naia_server & Bevy interop"
homepage = "https://github.com/naia-rs/naia"
repository = "https://github.com/naia-rs/naia"
license = "MIT OR Apache-2.0"
edition = "2018"

[badges]
maintenance = { status = "actively-developed" }

[features]
use-udp = [ "naia-server/use-udp" ]
use-webrtc = [ "naia-server/use-webrtc" ]

[dependencies]
naia-server = { version = "0.7.0", path = "../../../server" }
naia-bevy-shared = { version = "0.7.0", path = "../shared" }
bevy = { version="=0.6.0", default-features=false }