[package]
name = "naia-bevy-server"
version = "0.22.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
workspace = "../../.."
description = "Library to faciliate naia_server & Bevy interop"
homepage = "https://github.com/naia-lib/naia"
repository = "https://github.com/naia-lib/naia"
license = "MIT OR Apache-2.0"
edition = "2021"

[badges]
maintenance = { status = "actively-developed" }

[features]
transport_webrtc = [ "naia-server/transport_webrtc" ]
transport_udp = [ "naia-server/transport_udp" ]

[dependencies]
naia-server = { version = "0.22", path = "../../../server", features = ["bevy_support"] }
naia-bevy-shared = { version = "0.22", path = "../shared" }
bevy_app = { version = "0.13", default-features=false }
bevy_ecs = { version = "0.13", default-features=false }
log = { version = "0.4" }