[package]
name = "dev_http_server"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[[bin]]
name = "dev_http_server"
path = "src/main.rs"

[dependencies]
actix = { version = "=0.10.0" }
actix-web = { version = "=3.3.1" }
actix-web-actors = { version = "=3.0.0" }
actix-files = { version = "=0.3.0" }
env_logger = "0.8"